export enum ChannelsEventEnum {
  JOIN_CHANNELS = 'join_channels',
  NEW = 'new_channel',
  UPDATED = 'channel_updated',
  REMOVED = 'channel_removed',
  MEMBERS_COUNT = 'channel_members_count',
  UNREAD = 'unread_channel',
  UNREAD_TIMESTAMP = 'unread_channel_timestamp',
  NEW_MESSAGE = 'new_channel_message',
  SEND_MESSAGE = 'send_channel_message',
  UPDATE_MESSAGE = 'channel_update_message',
  MESSAGE_UPDATED = 'channel_message_updated',
  REMOVE_MESSAGE = 'channel_remove_message',
  MESSAGE_REMOVED = 'channel_message_removed',
}
